services:
  server:
    build:
      context: .
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - FLASK_ENV=${FLASK_ENV}
      - CLERK_BEARER_TOKEN_SECRET=${CLERK_BEARER_TOKEN_SECRET}
      - FRONTEND_SERVICE_URL=${FRONTEND_SERVICE_URL}
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dhparam/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/app.grainscan.in/fullchain.pem:/etc/letsencrypt/live/app.grainscan.in/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/app.grainscan.in/privkey.pem:/etc/letsencrypt/live/app.grainscan.in/privkey.pem
    networks:
      - app-network

networks:
  app-network:
    driver: bridge