
services:
  server:
    build:
      context: .
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - FLASK_ENV=${FLASK_ENV}
      - CLERK_BEARER_TOKEN_SECRET=${CLERK_BEARER_TOKEN_SECRET}
      - FRONTEND_SERVICE_URL=${FRONTEND_SERVICE_URL}
    platform: linux/amd64